<h1>Категории</h1>


<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Ключ</th>
            <th>Название</th>
            <th>Действие</th>
        </tr>
        <tr>
<?php
    foreach ($category as $item){?>

            <td><?php echo  $item->getId();  ?></td>
            <td><?php echo  $item->getCategoryKey();  ?></td>
            <td><?php echo  $item->getCategoryName();  ?></td>
        <?php   echo '<td><a href="'.$this->url('admin/category', array('action' => 'edit', 'id'=> $item->getId())).'">Редактировать</a>&nbsp;&nbsp;
                     <a href="'.$this->url('admin/category', array('action' => 'delete', 'id'=> $item->getId())).'" onclick="if (confirm(\'Удалить запись?\')) { document.location = this.href; } return false;">Удалить</a></td>';
    }
?>
             </tr>
    </tbody>
</table>

